<div id="select-form-view">
  
    
 <div class="select-form-view-item">
<input type="radio" id="select-form-view-1" name="select-form-view-1" data-name="default"/>
<label for="select-form-view-1"> Верстка </label>
<div class="read-code-button ui-state-default ui-corner-all button-16"><span class="ui-icon ui-icon-info"></span></div>
 </div>

<div class="select-form-view-item">
<input type="radio" id="select-form-view-2" name="select-form-view-2" data-name="users"  />
<label for="select-form-view-2">Табличная верстка</label>
<div class="read-code-button ui-state-default ui-corner-all button-16"><span class="ui-icon ui-icon-info"></span></div>
</div>


<div class="select-form-view-item">
<input type="radio" id="select-form-view-3" name="select-form-view-3" data-name="zendmyadmin"/>
<label for="select-form-view-3">Верстка дивами</label>
<div class="read-code-button ui-state-default ui-corner-all button-16"><span class="ui-icon ui-icon-info"></span></div>
</div>
 
<div class="select-form-view-item">
<input type="radio" id="select-form-view-4" name="select-form-view-4" data-name="" />
<label for="select-form-view-4">Очищенная верстка</label>
<div class="read-code-button ui-state-default ui-corner-all button-16"><span class="ui-icon ui-icon-info"></span></div>
</div>
 
<div class="select-form-view-item">
<input type="radio" id="select-form-view-5" name="select-form-view-5" data-name="" />
<label for="select-form-view-5">Только элементы ввода</label>
<div class="read-code-button ui-state-default ui-corner-all button-16"><span class="ui-icon ui-icon-info"></span></div>
</div>
 
</div>