<div id="creator-settings-switcher" class ="settings-status-panel-24 status-panel-left">
    <a class="icon-24 icon-zf-default-settings active" title="<?php echo $this->translate('zfmyadmin default settings');?>" data-type="zfmyadmin_settings_type"></a>
    <a class="icon-24 icon-zf-project-settings" title="<?php echo $this->translate('project default settings')?>"  data-type="project_settings_type"></a>
    <a class="icon-24 icon-zf-user-settings" title="<?php echo $this->translate('user settings')?>"  data-type="user_settings_type"></a>
</div>
