<form method="post" action="" enctype="application/x-www-form-urlencoded">
    <dl class="zend_form">
        <dt id="text_element-label">
            <label  for="text_element">Тексеовый элемент</label>
        </dt>
        <dd id="text_element-element">
            <input type="text" value="" id="text_element" name="text_element">
        </dd>
        <dt id="checkbox_element-label">
            <label  for="checkbox_element" >Чекбокс</label></dt>
        <dd id="checkbox_element-element">
            <input type="hidden" value="0" name="checkbox_element">
            <input type="checkbox" value="1" id="checkbox_element" name="checkbox_element">
        </dd>
        <dt id="submit_element-label">
            &nbsp;
        </dt>
        <dd id="submit_element-element">
            <input type="submit" value="Сабмит формы" id="submit_element" name="submit_element">
        </dd>
    </dl>
</form>
