<form method="post" action="" enctype="application/x-www-form-urlencoded">
    <div>
        <label  for="text_element">Тексеовый элемент</label>
        <input type="text" value="" id="text_element" name="text_element">
        
        <label  for="checkbox_element">Чекбокс</label>
        <input type="hidden" value="0" name="checkbox_element">
        <input type="checkbox" value="1" id="checkbox_element" name="checkbox_element">
        
        <label  for="submit_element">Сабмит формы</label>
        <input type="submit" value="Сабмит формы" id="submit_element" name="submit_element">
    </div>
</form>
