<form method="post" action="" enctype="application/x-www-form-urlencoded">
    <table>
        <tr>
            <td id="text_element-label">
                <label class="optional" for="text_element">Текстовый элемент</label>
            </td>
            <td class="element">
                <input type="text" value="" id="text_element" name="text_element"/>
            </td>
        </tr>
        <tr>
            <td id="checkbox_element-label">
                <label class="optional" for="checkbox_element">Чекбокс</label>
            </td>
            <td class="element">
                <input type="hidden" value="0" name="checkbox_element"/>
                <input type="checkbox" value="1" id="checkbox_element" name="checkbox_element"/>
            </td>
        </tr>
        <tr>
            <td id="submit_element-label">
                <label class="optional" for="submit_element">Сабмит формы</label>
            </td>
            <td class="element">
                <input type="submit" value="Сабмит формы" id="submit_element" name="submit_element"/>
            </td>
        </tr>
    </table>
</form>
