<form method="post" action="" enctype="application/x-www-form-urlencoded">
    <div>
        <div class="element-container">
            <div id="text_element-label">
                <label class="element-label" for="text_element">Тексеовый элемент</label>
            </div>
            <div class="element">
                <input type="text" value="" id="text_element" name="text_element">
            </div>
        </div>
        <div class="element-container">
            <div id="checkbox_element-label">
                <label class="element-label" for="checkbox_element">Чекбокс</label></div>
            <div class="element">
                <input type="hidden" value="0" name="checkbox_element">
                <input type="checkbox" value="1" id="checkbox_element" name="checkbox_element">
            </div>
        </div>
            <div class="element-container"><div id="submit_element-label">
                 <label class="element-label" for="submit_element">Сабмит формы</label>
            </div>
            <div class="element">
                <input type="submit" value="Сабмит формы" id="submit_element" name="submit_element">
            </div>
        </div>
    </div>
</form>
