    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>ZfMyAdmin</title>
    <link rel="stylesheet" href="/zfmyadmin_public/css/reset.css" type="text/css" media="all"  />

    <link type="text/css" href="/zfmyadmin_public/libs/jquery-ui/start/jquery-ui-1.8.23.custom.css" rel="stylesheet" />

    <link rel="stylesheet" href="/zfmyadmin_public/css/layout.css" type="text/css" media="all"  /> 
    

    <script type="text/javascript" src="/zfmyadmin_public/libs/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="/zfmyadmin_public/libs/jquery-ui/jquery-ui-1.8.23.custom.min.js"></script>
    
    <script type="text/javascript" src="/zfmyadmin_public/js/system.js"></script>
    <script type="text/javascript" src="/zfmyadmin_public/js/layout.js"></script>    
    
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript(); ?>
