<?php if(!empty($this->view->message)): ?>
    <div id="flash-message">
        <ul>
            <?php foreach ($this->view->message as $message) :?>
            <li>
                <?php  echo $message; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>    
<?php endif; ?>

<header id="header">
    <div id="logo">
        <a href="/zfmyadmin"></a>
    </div>
   <?php echo $this->action('get-languages',
           'partials',
           'zfmyadmin'); 
   ?>
   <div id="main-menu">  
       <?php if(!empty($this->view->user)): ?>
            <?php
                echo $this->navigation()
                    ->setAcl($this->view->acl)
                    ->setRole($this->view->user->role)
                    ->setContainer($this->zfmyadminMenu('main-menu'))                           
                    ->menu()
                    ->setUseTranslator(false) 
                    ;
             ?>
        <?php else: ?>
            <?php
                echo $this->navigation()
                    ->menu()    
                    ->setUseTranslator(false)                    
                    ->setContainer($this->zfmyadminMenu('login-menu'));
             ?>    
        <?php endif; ?>
    </div>
</header> 