<h1><?php echo $this->translate("Create Form");?></h1>
<?php
        if($_POST) {
	echo '<pre>';
		var_dump($_POST);
	echo '</pre>';
        
        }

?>

<div id="tooltip"></div>
<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" class ="<?php echo $this->form->getAttrib('class'); ?>">
    <div class="fieldset">
        <?php echo $this->partial('select-module-controller-action.phtml', $this);?>
    </div>
    
   
    <div class="fieldset">
        <div id="set-controller-settings-block" class="set-settings-block">
        <ul>
            <li><a href="#set-settings-block-class"><?php echo $this->translate("Class");?></a></li>
            <li><a href="#set-settings-block-form"><?php echo $this->translate("Form attributes");?></a></li>
            <li><a href="#set-settings-block-fields"><?php echo $this->translate("Fields");?></a></li>
	</ul> 
          
        <div id="set-settings-block-class">
                <div class="fieldset">
                    <h4><?php echo $this->translate("Class of form");?> </h4>
                    <?php echo $this->form->formClassName; ?>
                </div>
                <div class="fieldset">
                    <h4><?php echo $this->translate("Extends class of form");?> </h4>
                    <?php echo $this->form->formExtendsClassName; ?>
                </div>
        </div>   
        <div id="set-settings-block-form">           
                <?php
                    echo $this->form->attr;
                ?>
        </div> 
        <div id="set-settings-block-fields">
            <?php //echo $this->partial('router-block.phtml', array('form'=>$this->form));?>
            <table width="100%">
                <tr>
                    <th><?php echo $this->translate("Label");?></th>
                    <th><?php echo $this->translate("Name");?></th>
                    <th><?php echo $this->translate("Tag");?></th>
                    <th><?php echo $this->translate("Type");?></th>
                    <th><?php echo $this->translate("Edit");?></th>
                    <th><?php echo $this->translate("Delete");?></th>
                </tr>
                <tr>
                    <td>My name</td>
                    <td>username</td>
                    <td>input</td>
                    <td>text</td>
                    <td>
                        <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                             <span class="ui-icon ui-icon-circle-minus"></span>
                        </div>
                    </td>                    
                    <td>
                        <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                             <span class="ui-icon ui-icon-circle-minus"></span>
                        </div>
                    </td>
                </tr>                
            </table>
            <div id="form-add-field-button" title="<?php echo $this->translate('Add variable'); ?>" class="ui-state-default ui-corner-all button-16">
                <span class="ui-icon ui-icon-circle-plus"></span>
            </div>            
        </div>             
            
        </div>
    </div>    

    <?php echo $this->form->createSubmit; ?> 
    <?php echo $this->form->intentionSignature; ?>
    <?php echo $this->form->creatorCategory; ?>
    

</form>

<?php echo $this->partial("settings-buttons.phtml");?>