<h1><?php echo $this->translate("Create Route");?></h1>
<div id="tooltip"></div>
<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" class ="<?php echo $this->form->getAttrib('class'); ?>">
    <div class="fieldset">
        <?php echo $this->partial('select-module-controller-action.phtml', $this);?>
    </div>
    
   
    <div class="fieldset">
        <div id="set-controller-settings-block" class="set-settings-block">
        <ul>
            <li><a href="#set-settings-block-class"><?php echo $this->translate("Class");?></a></li>
            <li><a href="#set-settings-block-form"><?php echo $this->translate("Form settings");?></a></li>
            <li><a href="#set-settings-block-fields"><?php echo $this->translate("Fields");?></a></li>
	</ul> 
          
        <div id="set-settings-block-class">
                <div class="fieldset">
                    <h4><?php echo $this->translate("Class of form");?> </h4>
                    <?php echo $this->form->formClassName; ?>
                </div>
                <div class="fieldset">
                    <h4><?php echo $this->translate("Extends class of form");?> </h4>
                    <?php echo $this->form->formExtendsClassName; ?>
                </div>     
                <div class="fieldset">
                    <h4><?php echo $this->translate("Form name");?> </h4>
                    <?php echo $this->form->formName; ?>
                </div>              
        </div>   
        <div id="set-settings-block-form">
            <?php //echo $this->partial('router-block.phtml', array('form'=>$this->form));?>
        </div> 
        <div id="set-settings-block-fields">
            <?php //echo $this->partial('router-block.phtml', array('form'=>$this->form));?>
        </div>             
            
        </div>
    </div>    

    <?php echo $this->form->createSubmit; ?> 
    <?php echo $this->form->intentionSignature; ?>
    <?php echo $this->form->creatorCategory; ?>
</form>

<?php echo $this->partial("settings-buttons.phtml");?>