<h1><?php echo $this->translate("Create Form"); ?></h1>
<div id="tooltip"></div>
<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" class ="<?php echo $this->form->getAttrib('class'); ?>">
    <div class="fieldset">
        <?php echo $this->partial('select-module-controller-action.phtml', $this); ?>
    </div>


    <div class="fieldset">
        <div id="set-form-settings-block" class="set-settings-block">
            <ul>
                <li><a href="#set-settings-block-class"><?php echo $this->translate("Class"); ?></a></li>
                <li><a href="#set-settings-block-attributes"><?php echo $this->translate("Form attributes"); ?></a></li>
                <li><a href="#set-settings-block-design"><?php echo $this->translate("Design"); ?></a></li>
                <li><a href="#set-settings-block-fields"><?php echo $this->translate("Fields"); ?></a></li>
            </ul> 

            <div id="set-settings-block-class">
                <div class="fieldset">
                    <h4><?php echo $this->translate("Class of form"); ?> </h4>
                    <?php echo $this->form->formClassName; ?>
                </div>
                <div class="fieldset">
                    <h4><?php echo $this->translate("Extends class of form"); ?> </h4>
                    <?php echo $this->form->formExtendsClassName; ?>
                </div>
            </div>   
            <div id="set-settings-block-attributes">           
                <?php
                echo $this->form->attr;
                ?>
            </div> 
            <div id="set-settings-block-design" style=" height: 250px;  ">
                 <div id="show-form-design" style="float: right; height: 200px; width: 475px; background-color: #cccccc; overflow: auto">                     
                     <?php foreach ($this->showTemplateForms as $formKey => $formBody): ?>
                     <div class="design-type-preview" id="design-type-preview-<?php echo $formKey; ?>">
                     <pre><?php echo $formBody; ?></pre>
                     </div>
                     <?php endforeach; ?>
                </div>               
                <?php
                echo $this->form->design;
                ?>

            </div>             
            <div id="set-settings-block-fields">
                <?php //echo $this->partial('router-block.phtml', array('form'=>$this->form));?>
                <table width="100%">
                    <tr>
                        <th><?php echo $this->translate("Label"); ?></th>
                        <th><?php echo $this->translate("Name"); ?></th>
                        <th><?php echo $this->translate("Tag"); ?></th>
                        <th><?php echo $this->translate("Type"); ?></th>
                        <th><?php echo $this->translate("Edit"); ?></th>
                        <th><?php echo $this->translate("Delete"); ?></th>
                    </tr>
                    <tr>
                        <td>My name</td>
                        <td>username</td>
                        <td>input</td>
                        <td>text</td>
                        <td>
                            <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                                <span class="ui-icon ui-icon-circle-minus"></span>
                            </div>
                        </td>                    
                        <td>
                            <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                                <span class="ui-icon ui-icon-circle-minus"></span>
                            </div>
                        </td>
                    </tr> 

                    <?php foreach ($this->formfields as $field): ?>
                        <td><?php echo $field['general']['name']; ?></td>
                        <td><?php echo $field['general']['name']; ?></td>
                        <td><?php echo $field['general']['tag']; ?></td>
                        <td><?php echo $field['general']['type']; ?></td>
                        <td>
                            <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                                <span class="ui-icon ui-icon-circle-minus"></span>
                            </div>
                        </td>                    
                        <td>
                            <div data-number="0" title="Удалить переменную" class="ui-state-default ui-corner-all button-16 form-delete-field-button">
                                <span class="ui-icon ui-icon-circle-minus"></span>
                            </div>
                        </td>                


                    <?php endforeach; ?>
                </table>
                <div id="form-add-field-button" title="<?php echo $this->translate('Add variable'); ?>" class="ui-state-default ui-corner-all button-16">
                    <span class="ui-icon ui-icon-circle-plus"></span>
                </div>            
            </div>             

        </div>
    </div>    

    <?php echo $this->form->createSubmit; ?> 
    <?php echo $this->form->intentionSignature; ?>
    <?php echo $this->form->creatorCategory; ?>


</form>

<?php echo $this->partial("settings-buttons.phtml"); ?>
<div id="add-form-field-dialog" style="display: none" title="<?php echo $this->translate("Add/Edit field"); ?>">
    <form action="<?php echo $this->field->getAction(); ?>" method="<?php echo $this->field->getMethod(); ?>" id="<?php echo $this->field->getAttrib('id'); ?>" class ="<?php echo $this->field->getAttrib('class'); ?>">
        <div id="set-form-field-settings-block" class="set-settings-block">
            <ul>
                <li><a href="#set-form-field-general"><?php echo $this->translate("General"); ?></a></li>
                <li><a href="#set-form-field-design"><?php echo $this->translate("Design"); ?></a></li>
                <li><a href="#set-form-field-filters"><?php echo $this->translate("Filters"); ?></a></li>
                <li><a href="#set-form-field-validators"><?php echo $this->translate("Validators"); ?></a></li>
            </ul>
            <div id="set-form-field-general">
                <div>
                    <?php echo $this->field->general; ?>
                </div>

                <div id="add-field-tag-input" class="add-field-tag">
                    <?php echo $this->field->input; ?>
                </div>

                <div id="add-field-tag-select" style="display: none" class="add-field-tag">
                    <?php echo $this->field->select; ?>
                </div>

                <div id="add-field-tag-textarea" style="display: none" class="add-field-tag">
                    <?php echo $this->field->textarea; ?>
                </div> 
            </div>

            <div id="set-form-field-design">
                <?php echo $this->field->design; ?>
            </div>
            <div id="set-form-field-filters">
                <?php  echo $this->field->filters; ?>
            </div>
            <div id="set-form-field-validators">
                <?php  echo $this->field->validators; ?>
            </div>                


        </div>

        <?php echo $this->field->addFormFieldSubmit; ?>
        <?php echo $this->field->formType; ?>
    </form>
</div>
<script>
    $(function(){
        $('#create-form-formTag').bind('change', function(){
            var tabId = '#add-field-tag-'+$(this).val();
            $('div.add-field-tag').hide();
            $(tabId).show();            
        }) 
        
        $('input.has-options').bind('change',function(){
            if($(this).prop("checked")){
                $(this).parents(".add-form-element-validator-block").find(".create-form-element-validator-options").show();
            } else {
                $(this).parents(".add-form-element-validator-block").find(".create-form-element-validator-options").hide();
            }
        })
        
        $('input.design-type').bind('change',function(){
            var  type = $(this).val();
            $('div.design-type-preview').hide();
            $('#design-type-preview-'+type).show();            
        })
    })
</script>
<style>
    div.fieldset-left-40{
       width: 40%;
/*         float: left;*/
    }
    
    div.design-type-preview{
        display: none;
    }
</style>
